//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vucem_EEA.srvconsultarRemesas {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ventanillaunica.gob.mx/pedimentos/ws/service/consultarremesas", ConfigurationName="srvconsultarRemesas.ConsultarRemesasServicePortType")]
    public interface ConsultarRemesasServicePortType {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación consultarRemesas no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ventanillaunica.gob.mx/ventanilla/ConsultarRemesasService/consultarRem" +
            "esas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RespuestaBase))]
        Vucem_EEA.srvconsultarRemesas.consultarRemesasResponse consultarRemesas(Vucem_EEA.srvconsultarRemesas.consultarRemesasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ventanillaunica.gob.mx/ventanilla/ConsultarRemesasService/consultarRem" +
            "esas", ReplyAction="*")]
        System.Threading.Tasks.Task<Vucem_EEA.srvconsultarRemesas.consultarRemesasResponse> consultarRemesasAsync(Vucem_EEA.srvconsultarRemesas.consultarRemesasRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/pedimentos/ws/oxml/consultarremesas")]
    public partial class ConsultarRemesasPeticion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long numeroOperacionField;
        
        private Peticion peticionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long numeroOperacion {
            get {
                return this.numeroOperacionField;
            }
            set {
                this.numeroOperacionField = value;
                this.RaisePropertyChanged("numeroOperacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Peticion peticion {
            get {
                return this.peticionField;
            }
            set {
                this.peticionField = value;
                this.RaisePropertyChanged("peticion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/pedimentos/ws/oxml/comunes")]
    public partial class Peticion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int aduanaField;
        
        private int patenteField;
        
        private long pedimentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int aduana {
            get {
                return this.aduanaField;
            }
            set {
                this.aduanaField = value;
                this.RaisePropertyChanged("aduana");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int patente {
            get {
                return this.patenteField;
            }
            set {
                this.patenteField = value;
                this.RaisePropertyChanged("patente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long pedimento {
            get {
                return this.pedimentoField;
            }
            set {
                this.pedimentoField = value;
                this.RaisePropertyChanged("pedimento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/pedimentos/ws/oxml/consultarremesas")]
    public partial class Remesa : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string comprobanteVEField;
        
        private uint remesaAgenteField;
        
        private uint remesaSAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string comprobanteVE {
            get {
                return this.comprobanteVEField;
            }
            set {
                this.comprobanteVEField = value;
                this.RaisePropertyChanged("comprobanteVE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public uint remesaAgente {
            get {
                return this.remesaAgenteField;
            }
            set {
                this.remesaAgenteField = value;
                this.RaisePropertyChanged("remesaAgente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public uint remesaSA {
            get {
                return this.remesaSAField;
            }
            set {
                this.remesaSAField = value;
                this.RaisePropertyChanged("remesaSA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConsultarRemesasRespuesta))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/common/ws/oxml/respuesta")]
    public partial class RespuestaBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool tieneErrorField;
        
        private string[][] errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool tieneError {
            get {
                return this.tieneErrorField;
            }
            set {
                this.tieneErrorField = value;
                this.RaisePropertyChanged("tieneError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("mensaje", typeof(string), IsNullable=false)]
        public string[][] error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/pedimentos/ws/oxml/consultarremesas")]
    public partial class ConsultarRemesasRespuesta : RespuestaBase {
        
        private Remesa[] remesasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("remesas", Order=0)]
        public Remesa[] remesas {
            get {
                return this.remesasField;
            }
            set {
                this.remesasField = value;
                this.RaisePropertyChanged("remesas");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarRemesasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ventanillaunica.gob.mx/pedimentos/ws/oxml/consultarremesas", Order=0)]
        public Vucem_EEA.srvconsultarRemesas.ConsultarRemesasPeticion consultarRemesasPeticion;
        
        public consultarRemesasRequest() {
        }
        
        public consultarRemesasRequest(Vucem_EEA.srvconsultarRemesas.ConsultarRemesasPeticion consultarRemesasPeticion) {
            this.consultarRemesasPeticion = consultarRemesasPeticion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarRemesasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ventanillaunica.gob.mx/pedimentos/ws/oxml/consultarremesas", Order=0)]
        public Vucem_EEA.srvconsultarRemesas.ConsultarRemesasRespuesta consultarRemesasRespuesta;
        
        public consultarRemesasResponse() {
        }
        
        public consultarRemesasResponse(Vucem_EEA.srvconsultarRemesas.ConsultarRemesasRespuesta consultarRemesasRespuesta) {
            this.consultarRemesasRespuesta = consultarRemesasRespuesta;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConsultarRemesasServicePortTypeChannel : Vucem_EEA.srvconsultarRemesas.ConsultarRemesasServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultarRemesasServicePortTypeClient : System.ServiceModel.ClientBase<Vucem_EEA.srvconsultarRemesas.ConsultarRemesasServicePortType>, Vucem_EEA.srvconsultarRemesas.ConsultarRemesasServicePortType {
        
        public ConsultarRemesasServicePortTypeClient() {
        }
        
        public ConsultarRemesasServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultarRemesasServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultarRemesasServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultarRemesasServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vucem_EEA.srvconsultarRemesas.consultarRemesasResponse Vucem_EEA.srvconsultarRemesas.ConsultarRemesasServicePortType.consultarRemesas(Vucem_EEA.srvconsultarRemesas.consultarRemesasRequest request) {
            return base.Channel.consultarRemesas(request);
        }
        
        public Vucem_EEA.srvconsultarRemesas.ConsultarRemesasRespuesta consultarRemesas(Vucem_EEA.srvconsultarRemesas.ConsultarRemesasPeticion consultarRemesasPeticion) {
            Vucem_EEA.srvconsultarRemesas.consultarRemesasRequest inValue = new Vucem_EEA.srvconsultarRemesas.consultarRemesasRequest();
            inValue.consultarRemesasPeticion = consultarRemesasPeticion;
            Vucem_EEA.srvconsultarRemesas.consultarRemesasResponse retVal = ((Vucem_EEA.srvconsultarRemesas.ConsultarRemesasServicePortType)(this)).consultarRemesas(inValue);
            return retVal.consultarRemesasRespuesta;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vucem_EEA.srvconsultarRemesas.consultarRemesasResponse> Vucem_EEA.srvconsultarRemesas.ConsultarRemesasServicePortType.consultarRemesasAsync(Vucem_EEA.srvconsultarRemesas.consultarRemesasRequest request) {
            return base.Channel.consultarRemesasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vucem_EEA.srvconsultarRemesas.consultarRemesasResponse> consultarRemesasAsync(Vucem_EEA.srvconsultarRemesas.ConsultarRemesasPeticion consultarRemesasPeticion) {
            Vucem_EEA.srvconsultarRemesas.consultarRemesasRequest inValue = new Vucem_EEA.srvconsultarRemesas.consultarRemesasRequest();
            inValue.consultarRemesasPeticion = consultarRemesasPeticion;
            return ((Vucem_EEA.srvconsultarRemesas.ConsultarRemesasServicePortType)(this)).consultarRemesasAsync(inValue);
        }
    }
}
